Business app
U2-LABS/auth-playground pull request #1
Opened 2020-11-26 14:49 UTC by Stashchen

Pull request with business app code

2020-12-09 16:27 UTC, misterw approved these changes
Вроде все норм

2020-12-17 19:24 UTC, shurph requested changes

2020-12-17 19:24 UTC, shurph commented on business-app/src/frontend/src/components/App.js
> +    this.redirect_uri = 'http://localhost:3000/';
такие вещи лучше выносить в отдельный фалй, settings.js, config.js или что-то такое

2020-12-17 19:24 UTC, shurph commented on business-app/src/frontend/src/components/App.js
> +    this.redirect_uri = 'http://localhost:3000/';
в идеале, возможно, стоит значение таким переменные устанавливать на этапе билда из переменных окружения (и брать какие-то дефолтные значения, если нет значений в переменных окружения)

2020-12-17 19:24 UTC, shurph commented on business-app/src/frontend/src/components/App.js
> +      if (this.state.needRefresh) {
немного цепляется глаз за то, что часть переменных - в одном стиле написания (snake_case), а часть — в другом (camelCase). надо бы это к одному знаменателю как-то приводить

2020-12-17 19:24 UTC, shurph commented on business-app/src/frontend/src/components/UserDataList.js
> +        for (let item in this.state.userData) {
```js
let products = Object.entries(this.state.userData).map(
  ([key, val]) => <li key={key}>{key} ----- {val}</li>
)
```

2020-12-30 14:42 UTC, shurph approved these changes

2020-12-30 14:44 UTC, shurph commented
@Stashchen возник конфликт в изменениях из-за уже вмерженых изменений. Обнови пожалуйста пул реквест.

2021-01-04 19:34 UTC, Stashchen commented
Я решил конфликт с Readme. Можно ли сделать merge с основной веткой, чтобы можно было сделать docker-compose для всех 3-х сервисов

2021-01-06 20:05 UTC, merged