[WIP] Auth-portal
U2-LABS/auth-playground pull request #2
Opened 2020-12-01 17:48 UTC by JuliusChrona

2020-12-14 15:05 UTC, greatleroy commented on auth-portal/auth-portal/profiles/views.py
> +                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
Не имеет смысла передавать значение в `backend`, ведь он уже определён в `settings.py` в переменной `AUTHENTICATION_BACKENDS `

2020-12-14 15:06 UTC, greatleroy commented
LGTM +1

2020-12-14 17:26 UTC, JuliusChrona commented on auth-portal/auth-portal/profiles/views.py
> +                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
Это был прах былой мечты и неисполненных надежд :)
Больше его нет

2020-12-14 17:26 UTC, JuliusChrona commented on auth-portal/auth-portal/api/serializers.py
> +        field_names = super(ApplicationSerializer, self).get_field_names(*args, **kwargs)
Доп логика не пригодилась, метод убран ^_^

2020-12-17 18:58 UTC, shurph requested changes

2020-12-17 18:58 UTC, shurph commented on auth-portal/auth-portal/api/services.py
> +    BASE_DATA_SERVICE_PATH = "http://192.168.32.89:8000"
такие вещи лучше не прибивать гвоздями прям в недрах кода, а выносить в сеттинги
а в сеттингах брать эти настройки через переменные окружения, пусть даже оставляя дефолтное значение для тех, кто переменные окружения не указал

2020-12-17 18:58 UTC, shurph commented on auth-portal/auth-portal/api/services.py
> +        req = s.prepare_request(req)
выглядит несколько переусложнённо.
почему здесь не получилось использовать простой вариант?
```python
requests.get(..., cookies=cookies)
```

2020-12-17 18:58 UTC, shurph commented on auth-portal/auth-portal/api/views.py
> +        data = {field: user.serializable_value(field) for field in UserSerializer.Meta.fields}
зачем здесь использовать обход мета-информации сериализатора, а не использовать непосредственно сам сериализатор?

2020-12-17 18:58 UTC, shurph commented on auth-portal/auth-portal/api/views.py
> +        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
значения, пришедшие постом в апи вьюху, было бы неплохо тоже как-то валидировать
для этого можно использовать те же сериализаторы, сделанные специально для request параметров

2020-12-18 07:47 UTC, JuliusChrona commented on auth-portal/auth-portal/api/services.py
> +    BASE_DATA_SERVICE_PATH = "http://192.168.32.89:8000"
Переменные вынесены в settings и добавленные в .env

2020-12-18 07:52 UTC, JuliusChrona commented on auth-portal/auth-portal/api/views.py
> +        data = {field: user.serializable_value(field) for field in UserSerializer.Meta.fields}
Это был тестовый функционал

2020-12-18 07:52 UTC, JuliusChrona commented on auth-portal/auth-portal/api/views.py
> +        data = {field: user.serializable_value(field) for field in UserSerializer.Meta.fields}
Убрано

2020-12-18 07:52 UTC, JuliusChrona commented on auth-portal/auth-portal/api/views.py
> +        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
Это был тестовый функционал.
Убрано

2020-12-18 08:53 UTC, JuliusChrona commented on auth-portal/auth-portal/api/views.py
> +        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
Добавил валидацию с помощью сериализатора

2020-12-18 08:53 UTC, JuliusChrona commented on auth-portal/auth-portal/api/views.py
> +        data = {field: user.serializable_value(field) for field in UserSerializer.Meta.fields}
Измененено на непосредственное использование сериализатора

2020-12-18 10:36 UTC, JuliusChrona commented on auth-portal/auth-portal/api/services.py
> +        req = s.prepare_request(req)
До этого была идея встраивать сессию с первого сервиса в request, в итоге реализация изменилась. Сейчас уже это не надо, изменил на простой запрос
```Python
request.get(url, cookies=cookies)

2020-12-30 12:11 UTC, shurph commented
@JuliusChrona , сделай ребейз относитльно свежего мастера пожалуйста. Сегодня изменения в `.gitignore` конфликтуют.

2020-12-30 13:39 UTC, JuliusChrona commented
> @JuliusChrona , сделай ребейз относитльно свежего мастера пожалуйста. Сегодня изменения в `.gitignore` конфликтуют.

Done :)

2020-12-30 13:47 UTC, JuliusChrona commented
> @JuliusChrona , сделай ребейз относитльно свежего мастера пожалуйста. Сегодня изменения в `.gitignore` конфликтуют.

Done :)

2020-12-30 14:39 UTC, merged