[WIP] Dev source of truth
U2-LABS/auth-playground pull request #3
Opened 2020-12-03 16:44 UTC by NikDark

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +def Auth(request):
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                email = "".join([first_name, "@mail.ru"])
А почему просто не использовать ` email = first_name + "@mail.ru"`? Какая необходимость оформлять это через join?

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +def GetAllPerson(request):
Function names should be lowercase, with words separated by underscores as necessary to improve readability.
PS: не забудь исправить подобные ошибки по всему коду.

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                    new_user = User.objects.create_user(username=first_name, password=password, email=email, phone=phone, skype=skype, first_name=first_name, last_name=last_name)
В следующий раз попробуй хранить пароль более секьюрно:)

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/source_of_truth/views.py
> +        users = UserModel.objects.all()
Иногда не имеет смысла разбивать на несколько строк.  Ничем не отличалось бы, если бы ты сделал `get_user_model().objects.all()`

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +            personId_obj = url.get('personId', None)
стиль именования переменных  в python `snakecase_`. Просмотри, пожалуйста, весь код и исправь.
Возможно, ты хочешь в некоторых случаях видеть обратную совместимость в наименовании переменных, но она тут не к месту.

2020-12-13 21:56 UTC, greatleroy commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +FIELDS = ['Email', 'Username', 'First_Name', 'Last_Name', 'Phone', 'Skype']
Я бы переименовал эту переменную в что-то типо `USER_FIELDS` и сразу бы в правильном формате описал их, т.к. ты потом применяешь `field_name.lower()` метод.

2020-12-14 12:32 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +def Auth(request):
Исправил

2020-12-14 12:34 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                    new_user = User.objects.create_user(username=first_name, password=password, email=email, phone=phone, skype=skype, first_name=first_name, last_name=last_name)
Это тестовые данные. В базе данных они шифруюются при добавлении user через create_user

2020-12-14 12:34 UTC, NikDark commented on source-of-truth/source_of_truth/source_of_truth/views.py
> +        users = UserModel.objects.all()
Исправил
Просто думал в дальнейшем использовать UserModel, но не понадобилось

2020-12-14 12:34 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +            personId_obj = url.get('personId', None)
Исправил во всем коде

2020-12-14 12:37 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +FIELDS = ['Email', 'Username', 'First_Name', 'Last_Name', 'Phone', 'Skype']
У меня по ТЗ надо было отправлять JSON с ключами которые имеют такие поля, но когда я получаю данные о User через __getattribute__, то там используется lower()
Поэтому там либо lower() либо capitalize()

2020-12-14 12:37 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +def GetAllPerson(request):
Исправил

2020-12-14 12:40 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                email = "".join([first_name, "@mail.ru"])
Исправил
Просто слышал такое что join работает быстрее и лучше его, но наверное в данном случае не разумно использовать join, так как много строк не соединяются и это не явно

2020-12-14 15:23 UTC, greatleroy commented
LGTM +1

2020-12-17 18:43 UTC, shurph requested changes

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +        with open(options['first_name'], 'r') as first_name_file, open(options['last_name'], 'r') as last_name_file:
Имена и фамилии пользователей вычитываются из отдельных файлов, которые кем-то заранее случайно сгенерированы?

Тут лучше использовать factoryboy, который умеет генерировать рандомные правдоподобные имена людей, адреса и т.п. вещи

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                    new_user = get_user_model().objects.create_user(
`get_user_model()` можно ссделать единожды, и в цикле уже обращаться к переменной:
```python
...
User  = get_user_model()

class Command(...):
    ...
    def handle(...):
        ...
        for _ in range(...):
            new_user = User.objects.create_user(...)
```

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +        bar.finish()
Классная тема с прогресс-баром :+1:

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +            "SessionId": session_id,
это частая практика - смешивать ожидаемый из-вне PascalCase с принятым внутри питона snake_case.
но, всё же, внутри питоновского кода сильно приятнее смотреть на snake_case варианты.
для того, чтобы в итоге конечному пользователю отдавался привычный им PascalCase, можно использовать Middleware, который будет прозрачно преобразовывать все исходящие snake_case json ответы в PascalCase ответы, а также преобразовывать все входящие PascalCase json реквесты в snake_case реквсеты

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +            "SessionId": session_id,
см. https://github.com/miphreal/drf-tweaks/

2020-12-17 18:43 UTC, shurph commented on source-of-truth/source_of_truth/templates/source_of_truth/index.html
> +                <img class="avatar" src="https://blog.mystart.com/wp-content/uploads/shutterstock_224423782-e1524166038524.jpg" alt="avatar" width="70px" height="70px"/>
здесь для красоты можно было бы использовать аватары от gravatar, например, на основе их емейлов

2020-12-21 12:29 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +        with open(options['first_name'], 'r') as first_name_file, open(options['last_name'], 'r') as last_name_file:
Убрал чтение имен и фамилий из файла
Добавил рандомную генерацию имен и фамилий с помощью библиотеки Faker

2020-12-21 12:29 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +                    new_user = get_user_model().objects.create_user(
Не заметил сразу
Уже исправил

2020-12-21 12:30 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/management/commands/fill_users.py
> +        bar.finish()
Спасибо :wink:

2020-12-21 12:31 UTC, NikDark commented on source-of-truth/source_of_truth/templates/source_of_truth/index.html
> +                <img class="avatar" src="https://blog.mystart.com/wp-content/uploads/shutterstock_224423782-e1524166038524.jpg" alt="avatar" width="70px" height="70px"/>
Да, добавил свой собственный тег который генерирует ссылку на картинку из Gravatar и по умолчанию установил тип картинки identicon

2020-12-22 08:35 UTC, NikDark commented on source-of-truth/source_of_truth/auth_system_api/views.py
> +            "SessionId": session_id,
Добавил собственную middleware `ResponeMiddleware`

2020-12-29 20:46 UTC, shurph approved these changes

2020-12-29 20:47 UTC, merged