Docker-compose for all services
U2-LABS/auth-playground pull request #4
Opened 2021-01-07 19:20 UTC by Stashchen

Created docker files for all services.
Updated docker-compose and added postgres db container
Updated db settings of all the projects

2021-01-13 09:06 UTC, shurph requested changes

2021-01-13 09:06 UTC, shurph commented on source-of-truth/Dockerfile
> +FROM ubuntu:latest
Использование latest может привести к непредсказуемым последствиям, когда версия убунты обновится. Вплоть до нерабочего состояния приложения.

2021-01-13 09:06 UTC, shurph commented on README.md
> +docker-compose up -d
желательно сделать файл `.env.example`, в котором перечислить все переменные окружения с примерными значениями, которые нужны для старта приложения. и упомянуть этот файлв в README

2021-01-13 09:24 UTC, Stashchen commented on README.md
> +docker-compose up -d
А надо создать _.env.example_ для каждого сервиса, чтобы можно было их запускать поодиночке или же один общий файл?

2021-01-13 09:34 UTC, Stashchen commented on source-of-truth/Dockerfile
> +FROM ubuntu:latest
Поставил версию 20.04 для ubuntu images

2021-01-14 20:33 UTC, shurph commented on README.md
> +docker-compose up -d
если они вче через один общий набор переменных окружения запускаются, тогда один общий

2021-01-15 14:27 UTC, Stashchen commented on README.md
> +docker-compose up -d
Я сделал один `.env.example`файл, в котором описал переменные окужения для всех 3-х сервисов

2021-01-15 16:35 UTC, shurph approved these changes

2021-01-15 16:36 UTC, merged